<a href="https://colab.research.google.com/github/selvagit/experiments/blob/master/udemy/pytorch-for-deep-learning/PyTorchforDeepLearningBootcamp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch.nn as nn
print(torch.cuda.is_available())
print(torch.__version__)

False
2.9.0+cpu


### Introduction to tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [5]:
# dimension is based on number of the square brackets
vector.ndim

1

In [6]:
vector.shape

torch.Size([2])

In [7]:
matrix =torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
matrix.ndim

2

In [9]:
matrix[1]

tensor([ 9, 10])

In [10]:
matrix.shape

torch.Size([2, 2])

In [11]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
TENSOR.ndim


3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [14]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [15]:
TENSOR[0][1]


tensor([3, 6, 9])

### Random tensors

why random tensors ?

Random tensors are important because the way many neural network learn is that they start with tensors full of random number and then adjust the those random numbers to better represent the data


In [16]:
#create a random tensor
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.8447, 0.0361, 0.6307, 0.3794],
        [0.8509, 0.5228, 0.0759, 0.9318],
        [0.3239, 0.1983, 0.5244, 0.4989]])

In [17]:
random_tensor.ndim

2

In [18]:
random_tensor.shape

torch.Size([3, 4])

In [19]:
# create a random tensor with similar share of an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) #height , width , colour channel
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [20]:
zero =torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
zero *random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
ones =torch.ones(size=(3,4))
ones , ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

# Creating a range of tensors and tensors-like

In [23]:
# use torch.arange()
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
torch.__version__

'2.9.0+cpu'

In [25]:
one_to_ten = torch.arange(start=1,end=1000,step=77)
one_to_ten

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [26]:
# creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor datatypes

**Note:** 3 big errors
1. tensor not right datatype
2. tensor not in corrrect shape
3. tensor not in correct device


In [27]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0])
float_32_tensor1 = torch.tensor([3.0,6.0,9.0],
                                dtype=None,
                                device=None,
                                requires_grad=False
                                )
float_32_tensor1 , float_32_tensor1.dtype

(tensor([3., 6., 9.]), torch.float32)

In [28]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [29]:
tensor_mult = float_16_tensor * float_32_tensor1
tensor_mult , tensor_mult.dtype

(tensor([ 9., 36., 81.]), torch.float32)

In [30]:
int_32_tensor = torch.tensor([1,3,4],dtype=torch.int32)

In [31]:
### getting type
tensor_mult.dtype, tensor_mult.shape , tensor_mult.device

(torch.float32, torch.Size([3]), device(type='cpu'))

### Manipulating tensors

Tensoe operation include:
* Addition
* Subtraction
* Multiplication
* Matrix multiplication
* Division

In [32]:
# create a tensor and add 10
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [33]:
# tensors by 10
tensor*10

tensor([10, 20, 30])

In [34]:
# tensor - 10
tensor -10

tensor([-9, -8, -7])

In [35]:
# pytrouch inbuilt function
torch.mul(tensor,10)

tensor([10, 20, 30])

In [36]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix multiplication

In [37]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]

CPU times: user 0 ns, sys: 687 µs, total: 687 µs
Wall time: 692 µs


In [38]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 3 µs, sys: 873 µs, total: 876 µs
Wall time: 13 ms


tensor(14)

### common error
1. Shape error, inner dimension must match
* '(3,2) @ (3,2)' would not work
* '(2,3) @ (3,2)' will work
* '(3,2) @ (2,3)' will work
2. The result matrix has the shapre of the **outer dimensions**
* '(2,3) @ (3,2)' -> (2,2)
* '(3,2) @ (3,2)' -> wo'not work
* '(3,2) @ (2,3)' -> (3,3)

In [39]:
# torch.matmul(torch.rand(3,2), torch.rand(3,2))


In [40]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.3204, 0.1184, 0.1783],
        [0.3276, 0.2326, 0.2305],
        [0.3147, 0.3292, 0.2670]])

In [41]:
### multiplicatop
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
#torch.matmul(tensor_A,tensor_B)

In [42]:
### to fix out the error , transpose the error
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## finding the min,max,sum, etc (tensor aggregation)

In [45]:
# create a tensor
x = torch.arange(0,100,10)
print(f"max {torch.max(x), x.max()}")
print(f"min {torch.min(x), x.min()}")
print(f"sum {torch.sum(x), x.sum()}")

max (tensor(90), tensor(90))
min (tensor(0), tensor(0))
sum (tensor(450), tensor(450))


In [46]:
torch.mean(x.type(torch.float))

tensor(45.)